security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: username

    role_hierarchy:
        ROLE_ADMIN: [ROLE_EMPLOYEE, ROLE_VET]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/  # Exclusion des outils de développement
            security: false

        main:
            lazy: true
            provider: app_user_provider
            json_login:
                check_path: /api/login
                success_handler: App\Security\LoginSuccessHandler
                failure_handler: App\Security\LoginFailureHandler
            logout:
                path: /logout
                target: /
            security: true
            stateless: true  # Utilisation d'un API sans session

    access_control:
        - { path: ^/api/registration, roles: ROLE_ADMIN } 
        - { path: ^/services/new, roles: ROLE_ADMIN }
        - { path: ^/services/\d+/edit, roles: ROLE_ADMIN }
        - { path: ^/services/\d+, roles: ROLE_ADMIN, methods: [DELETE] }
        - { path: ^/avis/new, roles: ROLE_EMPLOYEE }
        - { path: ^/avis/\d+, roles: ROLE_EMPLOYEE, methods: [DELETE, PUT] }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/employee, roles: ROLE_EMPLOYEE }
        - { path: ^/vet, roles: ROLE_VET }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
