nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']  # Jeder Ursprung ist erlaubt
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'X-AUTH-TOKEN']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        expose_headers: []
        max_age: 3600
        hosts: [] 
    paths:
        '^/api/':  # CORS-Regeln für API-Endpunkte
            allow_origin: ['*']  # Alle Ursprünge sind für API-Pfade erlaubt
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'X-AUTH-TOKEN']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            max_age: 3600
            