# config/services.yaml
parameters:

services:
    _defaults:
        autowire: true     
        autoconfigure: true 

    # Configuration des services dans src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']  # Pas de type ici

    # Handlers pour la sécurité (success et failure)
    App\Security\LoginSuccessHandler:
        autowire: true
        autoconfigure: true

    App\Security\LoginFailureHandler:
        autowire: true
        autoconfigure: true
